apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hypershift-installer-role
  namespace: {{ .Values.metadata.name | quote }}
rules:
  - apiGroups: ["metal3.io"]
    resources:
      - baremetalhosts
    verbs:
      - list
  - apiGroups: ["agent-install.openshift.io"]
    resources:
      - agents
    verbs:
      - list
      - watch
  - apiGroups: ["hypershift.openshift.io"]
    resources:
      - nodepools
      - nodepools/scale
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hypershift-installer-binding
  namespace: {{ .Values.metadata.name | quote }}
subjects:
  - kind: ServiceAccount
    name: hypershift-installer
roleRef:
  kind: Role
  name: hypershift-installer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hypershift-installer
  namespace: {{ .Values.metadata.name | quote }}
