name: Build project

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Helm
        uses: azure/setup-helm@v5

      - name: Check code
        run: |
          ./tests/run_tests.sh
